# Generated by Django 5.2.1 on 2025-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default='static/devices_images/1.jpg', null=True, upload_to='devices_images/', verbose_name='设备图片'),
        ),
    ]
