# Generated by Django 5.2.1 on 2025-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceissue',
            name='is_handled',
            field=models.BooleanField(choices=[('True', '是'), ('False', '否')], default=False, verbose_name='是否处理'),
        ),
    ]
