# Generated by Django 5.2.1 on 2025-05-31 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_number', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('brand', models.CharField(max_length=50, verbose_name='品牌')),
                ('model', models.CharField(max_length=50, verbose_name='型号')),
                ('details', models.TextField(blank=True, null=True, verbose_name='设备详细信息')),
                ('status', models.CharField(choices=[('ok', '正常'), ('borrowed', '已借出'), ('maintenance', '维修中'), ('damaged', '已损坏')], default='ok', max_length=20, verbose_name='当前状态')),
                ('image', models.ImageField(blank=True, default='static/devices_images/1.jpg', null=True, upload_to='device_images/', verbose_name='设备图片')),
            ],
            options={
                'verbose_name': '设备总表',
                'verbose_name_plural': '设备总表',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='设备大类型')),
            ],
            options={
                'verbose_name': '设备大分类表',
                'verbose_name_plural': '设备大分类表',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借用日期')),
                ('estimated_return_date', models.DateTimeField(verbose_name='预估归还日期')),
                ('actual_return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('unreturned', '未归还'), ('returned', '已归还')], default='unreturned', max_length=20, verbose_name='当前状态')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备借用记录表',
                'verbose_name_plural': '设备借用记录表',
            },
        ),
        migrations.CreateModel(
            name='DeviceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上报日期')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否处理')),
                ('handle_result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('handle_date', models.DateTimeField(blank=True, null=True, verbose_name='处理日期')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='设备')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_issues', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
            ],
            options={
                'verbose_name': '设备异常记录表',
                'verbose_name_plural': '设备异常记录表',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='设备大类型'),
        ),
    ]
